# Generated by Django 4.0 on 2022-03-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='thumbnail_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='لینک محتوا'),
        ),
    ]
