# Generated by Django 4.0 on 2021-12-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_topics_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='topics',
            field=models.ManyToManyField(related_name='articles', to='blog.Topics', verbose_name='تاپیک'),
        ),
    ]
