# Generated by Django 4.0 on 2021-12-11 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_homecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار'),
        ),
    ]
