# Generated by Django 4.0 on 2021-12-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_homecontent_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontent',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='محتوا'),
        ),
    ]
