# Generated by Django 4.0 on 2021-12-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_homecontent_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='slug',
        ),
    ]
