# Generated by Django 4.0 on 2021-12-17 19:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='body',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='محتوا'),
        ),
    ]
